# Generated by Django 4.2.16 on 2024-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebiblioteka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
