# Generated by Django 4.2.16 on 2024-12-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebiblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
